### ISSUE TITLE
Support for Robolectric 3.5.1 (or higher)

### ISSUE THREAD

**Issue by nolia** [hkhc/electricspock#5]
Hi there! 🖖 
Trying to build project with Robolectric 3.5.1 and ElectricSpock 0.6, got:
```java.lang.RuntimeException: This version of ElectricSpock supports Robolectric 3.3 or 3.4 only```
  
Robolectric 3.4 had an issue with gradle plugin 3.0 and `aapt2` resources, that's why I cannot downgrade Robolectric itself.
Is there a huge effort on updating to latest Robolectric version? 👷

**Comment by hkhc** [comment]
ElectricSpock 0.7 is out. Have fun!

**Comment by nolia** [comment]
Cool! Thanks!
